spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: ${SPRING_CACHE_TYPE}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  cookie-secure: ${JWT_COOKIE_SECURE}
  cookie-same-site: ${JWT_COOKIE_SAME_SITE}
